# Generated by Django 4.2.9 on 2024-01-15 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistants',
            name='boss',
        ),
        migrations.RemoveField(
            model_name='assistants',
            name='user',
        ),
        migrations.AddField(
            model_name='assistants',
            name='assistant',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistants',
            name='psychologist',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.psychologists'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psychologists',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
