# Generated by Django 4.2.9 on 2024-01-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_assistants_boss_remove_assistants_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistants',
            old_name='assistant',
            new_name='user',
        ),
    ]
