# Generated by Django 4.2.9 on 2024-01-17 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_alter_patients_age_alter_patients_children_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('country_of_birth', models.CharField(blank=True, max_length=255)),
                ('city_of_birth', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=255)),
                ('country_of_residence', models.CharField(blank=True, max_length=255)),
                ('city_of_residence', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.CharField(blank=True, max_length=3)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('children', models.CharField(blank=True, max_length=255)),
                ('diseases', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Testings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tests', models.CharField(max_length=255)),
                ('results', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.RenameModel(
            old_name='Assistants',
            new_name='Assistant',
        ),
        migrations.RenameModel(
            old_name='Psychologists',
            new_name='Psychologist',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.AddField(
            model_name='testings',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.psychologist'),
        ),
        migrations.AddField(
            model_name='patient',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.psychologist'),
        ),
    ]
