# Generated by Django 4.2.9 on 2024-01-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_patient_testings_rename_assistants_assistant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testings',
            new_name='Testing',
        ),
    ]
