# Generated by Django 4.2.9 on 2024-01-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_testing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
