# Generated by Django 4.2.9 on 2024-01-17 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_testing_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
