# Generated by Django 4.2.9 on 2024-01-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_testing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='time',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testing',
            name='time_create',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
