# Generated by Django 4.2.9 on 2024-01-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_testing_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='access',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
